apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bright-prodigy-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: us-west2-docker.pkg.dev/brightprodigyapp/prod-images/bright-prodigy-app:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/server/google-credentials.json"
            - name: GOOGLE_SHEETS_ID
              value: "your-google-sheets-id"
            - name: GOOGLE_CALENDAR_ID
              value: "your-google-calendar-id"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 4
